### ISSUE TITLE
Video URL is incorrect

### ISSUE THREAD

**Issue by liberium** [hamzam0n/3D_objects_annotation#1]
For me it opens musical video.
<img width="942" alt="image" src="https://github.com/hamzam0n/3D_objects_annotation/assets/598848/f091dc71-7485-4464-ac73-b43e092b627e">

**Comment by hamzam0n** [comment]
i apologize, i wrote the wrong link,
here is the correct [link](https://youtu.be/HeLEH7P3ZAk )
